Repository DLR-AMR/semantic_version_test, pull requests merged in 2025-01, with the labels that each got.

#1 test
  version.txt
Labels: minor

#2 Major update
  version.txt
Labels: major

#3 Another major update
  version.txt
Labels: major

#4 Update Version
  version.txt
Labels: major

#5 Update Version
  version.txt
Labels: patch

#10 Only allow empty commits to update the version.
  update_version.scp
  version.txt
Labels: minor

#12 Revert "Only allow empty commits to update the version. "
  update_version.scp
  version.txt
Labels: patch

#11 Get latest tag from main
  update_version.scp
  version.txt
Labels: minor

#6 update runner [Test Sandro, please do not merge or edit]
  .github/workflows/semantic_version.yml
  version.txt
Labels: enhancement, patch

#7 remove runner update [Test Sandro, please do not merge or edit]
  .github/workflows/semantic_version.yml
  version.txt
Labels: enhancement, patch

#8 update checkout action [Test Sandro, do not merge or edit]
  .github/workflows/semantic_version.yml
  version.txt
Labels: enhancement, minor

#13 Ensure new version is larger
  update_version.scp
  version.txt
Labels: minor

#16 Update README.md
  README.md
  version.txt
Labels: patch

#17 T8DDY
  .github/workflows/semantic_version.yml
  update_version.scp
  version.txt
Labels: minor

#19 Add citation file
  CITATION.cff
  version.txt
Labels: patch

#18 split workflow into two
  .github/workflows/check_version_tag.yml
  .github/workflows/create_version_tag.yml
  update_version.scp
  version.txt
Labels: major

#20 check workflow
  .github/workflows/check_version_tag.yml
  CITATION.cff
  update_version.scp
  version.txt
Labels: patch

#22 Check that updating the minor version works.
  .github/workflows/check_version_tag.yml
  CITATION.cff
  version.txt
Labels: minor

#23 update patch version
  CITATION.cff
  version.txt
Labels: patch

#24 test major update
  CITATION.cff
  version.txt
Labels: major

#25 remove mail address
  CITATION.cff
  update_version.scp
  version.txt
Labels: patch
